// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Customer.Item.Comments.Item;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Customer.Item.Comments
{
    /// <summary>
    /// Builds and executes requests for operations under \customer\{customerCode-id}\comments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nexus.Casp.Client.customer.item.comments.item collection</summary>
        /// <param name="position">Filter comments on a specific comment Guid</param>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.Item.CommentsItemRequestBuilder"/></returns>
        public global::Nexus.Casp.Client.Customer.Item.Comments.Item.CommentsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Nexus.Casp.Client.Customer.Item.Comments.Item.CommentsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode%2Did}/comments{?limit*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode%2Did}/comments{?limit*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// List comments for a customer
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetCommentsResponsePagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.GetCommentsResponsePagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder.CommentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.GetCommentsResponsePagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder.CommentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.GetCommentsResponsePagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.GetCommentsResponsePagedResultCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List comments for a customer
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder.CommentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder.CommentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Customer.Item.Comments.CommentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List comments for a customer
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CommentsRequestBuilderGetQueryParameters 
        {
            /// <summary>Number of comments per page</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Get specific page.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
    }
}
#pragma warning restore CS0618
