// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Sendinternal.Custodian;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Sendinternal
{
    /// <summary>
    /// Builds and executes requests for operations under \sendinternal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendinternalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custodian property</summary>
        public global::Nexus.Casp.Client.Sendinternal.Custodian.CustodianRequestBuilder Custodian
        {
            get => new global::Nexus.Casp.Client.Sendinternal.Custodian.CustodianRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sendinternal.SendinternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendinternalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sendinternal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sendinternal.SendinternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendinternalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sendinternal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
