// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.LabelPartner.CryptoCurrencies
{
    /// <summary>
    /// Builds and executes requests for operations under \LabelPartner\cryptoCurrencies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CryptoCurrenciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CryptoCurrenciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LabelPartner/cryptoCurrencies{?cryptoCode*,limit*,page*,sortDirection*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CryptoCurrenciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LabelPartner/cryptoCurrencies{?cryptoCode*,limit*,page*,sortDirection*}", rawUrl)
        {
        }
        /// <summary>
        /// List LabelPartner crypto currencies
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrencyPagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrencyPagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder.CryptoCurrenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrencyPagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder.CryptoCurrenciesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrencyPagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrencyPagedResultCustomResultHolder.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List LabelPartner crypto currencies
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder.CryptoCurrenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder.CryptoCurrenciesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.LabelPartner.CryptoCurrencies.CryptoCurrenciesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List LabelPartner crypto currencies
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CryptoCurrenciesRequestBuilderGetQueryParameters 
        {
            /// <summary>Get crypto currencies for specific a crypto code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cryptoCode")]
            public string? CryptoCode { get; set; }
#nullable restore
#else
            [QueryParameter("cryptoCode")]
            public string CryptoCode { get; set; }
#endif
            /// <summary>Enter page limit</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Get specific page of crypto currencies</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Direction of the sort on the crypto currency codes.Possible values:- `Asc`- `Desc`</summary>
            [QueryParameter("sortDirection")]
            public global::Nexus.Casp.Client.Models.SortDirection? SortDirection { get; set; }
        }
    }
}
#pragma warning restore CS0618
