// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountProviderTypeDTO
    {
        [EnumMember(Value = "Undefined")]
        #pragma warning disable CS1591
        Undefined,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustodianSeparateAddress")]
        #pragma warning disable CS1591
        CustodianSeparateAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustodianOmnibus")]
        #pragma warning disable CS1591
        CustodianOmnibus,
        #pragma warning restore CS1591
        [EnumMember(Value = "SelfHosted")]
        #pragma warning disable CS1591
        SelfHosted,
        #pragma warning restore CS1591
    }
}
