// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AmountsResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cryptoAmount property</summary>
        public double? CryptoAmount { get; set; }
        /// <summary>The cryptoPrice property</summary>
        public double? CryptoPrice { get; set; }
        /// <summary>The fiatValue property</summary>
        public double? FiatValue { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.AmountsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.AmountsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.AmountsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cryptoAmount", n => { CryptoAmount = n.GetDoubleValue(); } },
                { "cryptoPrice", n => { CryptoPrice = n.GetDoubleValue(); } },
                { "fiatValue", n => { FiatValue = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("cryptoAmount", CryptoAmount);
            writer.WriteDoubleValue("cryptoPrice", CryptoPrice);
            writer.WriteDoubleValue("fiatValue", FiatValue);
        }
    }
}
#pragma warning restore CS0618
