// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BrokerBuyRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Nexus generated unique identifier of the account or combination of crypto code and address.Example: XLM-14DuxbRVYPSmt1c3f2UnoKVUHkR5bVB9oa</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountCode { get; set; }
#nullable restore
#else
        public string AccountCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 . _ @ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountNumber { get; set; }
#nullable restore
#else
        public string BankAccountNumber { get; set; }
#endif
        /// <summary>Message to be send to the Blockchain - given the Blockchain allows messages</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockchainMessage { get; set; }
#nullable restore
#else
        public string BlockchainMessage { get; set; }
#endif
        /// <summary>Url to send callback notifications on status updates to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>Code of the crypto currency which the transaction is processed in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Must be exactly 3 uppercase letters (A-Z). Example: EUR</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>Optional user defined data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.BrokerBuyRequest_data? Data { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.BrokerBuyRequest_data Data { get; set; }
#endif
        /// <summary>Must start with a letter or digit (A-Z, a-z, or 0-9), and can only consist of A-Z a-z 0-9 space , . / # &apos; -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationAddress { get; set; }
#nullable restore
#else
        public string DestinationAddress { get; set; }
#endif
        /// <summary>The amount of fiat currency the brokerbuy transaction should be created for.</summary>
        public decimal? FiatValue { get; set; }
        /// <summary>Code of the payment method which the transaction is processed with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodCode { get; set; }
#nullable restore
#else
        public string PaymentMethodCode { get; set; }
#endif
        /// <summary>Optional payment reference to associate with this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReference { get; set; }
#nullable restore
#else
        public string PaymentReference { get; set; }
#endif
        /// <summary>The BUY price at which the crypto currency will be bought.Nexus checks if the requested BUY price is within certain ranges (Wiggle room).Ranges:10% price increase allowed5% price reduction allowed</summary>
        public decimal? RequestedPrice { get; set; }
        /// <summary>Stage the transaction instead of directly executing it.An additional confirmation API call to commit the transaction is required to execute it.</summary>
        public bool? Stage { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.BrokerBuyRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.BrokerBuyRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.BrokerBuyRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCode", n => { AccountCode = n.GetStringValue(); } },
                { "bankAccountNumber", n => { BankAccountNumber = n.GetStringValue(); } },
                { "blockchainMessage", n => { BlockchainMessage = n.GetStringValue(); } },
                { "callbackUrl", n => { CallbackUrl = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Nexus.Casp.Client.Models.BrokerBuyRequest_data>(global::Nexus.Casp.Client.Models.BrokerBuyRequest_data.CreateFromDiscriminatorValue); } },
                { "destinationAddress", n => { DestinationAddress = n.GetStringValue(); } },
                { "fiatValue", n => { FiatValue = n.GetDecimalValue(); } },
                { "paymentMethodCode", n => { PaymentMethodCode = n.GetStringValue(); } },
                { "paymentReference", n => { PaymentReference = n.GetStringValue(); } },
                { "requestedPrice", n => { RequestedPrice = n.GetDecimalValue(); } },
                { "stage", n => { Stage = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountCode", AccountCode);
            writer.WriteStringValue("bankAccountNumber", BankAccountNumber);
            writer.WriteStringValue("blockchainMessage", BlockchainMessage);
            writer.WriteStringValue("callbackUrl", CallbackUrl);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.BrokerBuyRequest_data>("data", Data);
            writer.WriteStringValue("destinationAddress", DestinationAddress);
            writer.WriteDecimalValue("fiatValue", FiatValue);
            writer.WriteStringValue("paymentMethodCode", PaymentMethodCode);
            writer.WriteStringValue("paymentReference", PaymentReference);
            writer.WriteDecimalValue("requestedPrice", RequestedPrice);
            writer.WriteBoolValue("stage", Stage);
        }
    }
}
#pragma warning restore CS0618
