// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateNotificationType
    {
        [EnumMember(Value = "Operational")]
        #pragma warning disable CS1591
        Operational,
        #pragma warning restore CS1591
        [EnumMember(Value = "Technical")]
        #pragma warning disable CS1591
        Technical,
        #pragma warning restore CS1591
    }
}
