// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateTransferModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Transfer&apos;s amount in crypto.</summary>
        public double? Amount { get; set; }
        /// <summary>Unique identifier of a crypto.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>If the sink is Exchange, it provides its unique exchange code.&lt;example&gt;KRAKEN&lt;/example&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SinkExchangeCode { get; set; }
#nullable restore
#else
        public string SinkExchangeCode { get; set; }
#endif
        /// <summary>Describes a transfer&apos;s sink type.</summary>
        public global::Nexus.Casp.Client.Models.TransferAddressType? SinkType { get; set; }
        /// <summary>If the source is Exchange, it provides its unique exchange code.&lt;example&gt;KRAKEN&lt;/example&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceExchangeCode { get; set; }
#nullable restore
#else
        public string SourceExchangeCode { get; set; }
#endif
        /// <summary>Describes a transfer&apos;s source type.</summary>
        public global::Nexus.Casp.Client.Models.TransferAddressType? SourceType { get; set; }
        /// <summary>The transferAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransferAddress { get; set; }
#nullable restore
#else
        public string TransferAddress { get; set; }
#endif
        /// <summary>Username (Optional)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateTransferModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CreateTransferModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CreateTransferModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "sinkExchangeCode", n => { SinkExchangeCode = n.GetStringValue(); } },
                { "sinkType", n => { SinkType = n.GetEnumValue<global::Nexus.Casp.Client.Models.TransferAddressType>(); } },
                { "sourceExchangeCode", n => { SourceExchangeCode = n.GetStringValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::Nexus.Casp.Client.Models.TransferAddressType>(); } },
                { "transferAddress", n => { TransferAddress = n.GetStringValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("sinkExchangeCode", SinkExchangeCode);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.TransferAddressType>("sinkType", SinkType);
            writer.WriteStringValue("sourceExchangeCode", SourceExchangeCode);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.TransferAddressType>("sourceType", SourceType);
            writer.WriteStringValue("transferAddress", TransferAddress);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
