// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAccountRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountType { get; set; }
#nullable restore
#else
        public string AccountType { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketCode { get; set; }
#nullable restore
#else
        public string BucketCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Settings required for creating a custodian based account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CustodianSettingsRequest? CustodianSettings { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CustodianSettingsRequest CustodianSettings { get; set; }
#endif
        /// <summary>Crypto address of the new account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCryptoAddress { get; set; }
#nullable restore
#else
        public string CustomerCryptoAddress { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcCode { get; set; }
#nullable restore
#else
        public string DcCode { get; set; }
#endif
        /// <summary>IP of the customer. For logging and analytics.Deprecated: Use customer_ip_address header insteadMust be a valid IPv4 or IPv6 address. Examples: 192.168.1.1, 2001db8::1</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ip { get; set; }
#nullable restore
#else
        public string Ip { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeAccountCode { get; set; }
#nullable restore
#else
        public string NativeAccountCode { get; set; }
#endif
        /// <summary>Represents the wallet service provider information for an account,including the provider type and provider name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.AccountProvider? Provider { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.AccountProvider Provider { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateAccountRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CreateAccountRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CreateAccountRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountType", n => { AccountType = n.GetStringValue(); } },
                { "bucketCode", n => { BucketCode = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "custodianSettings", n => { CustodianSettings = n.GetObjectValue<global::Nexus.Casp.Client.Models.CustodianSettingsRequest>(global::Nexus.Casp.Client.Models.CustodianSettingsRequest.CreateFromDiscriminatorValue); } },
                { "customerCryptoAddress", n => { CustomerCryptoAddress = n.GetStringValue(); } },
                { "dcCode", n => { DcCode = n.GetStringValue(); } },
                { "ip", n => { Ip = n.GetStringValue(); } },
                { "nativeAccountCode", n => { NativeAccountCode = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetObjectValue<global::Nexus.Casp.Client.Models.AccountProvider>(global::Nexus.Casp.Client.Models.AccountProvider.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountType", AccountType);
            writer.WriteStringValue("bucketCode", BucketCode);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CustodianSettingsRequest>("custodianSettings", CustodianSettings);
            writer.WriteStringValue("customerCryptoAddress", CustomerCryptoAddress);
            writer.WriteStringValue("dcCode", DcCode);
            writer.WriteStringValue("ip", Ip);
            writer.WriteStringValue("nativeAccountCode", NativeAccountCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.AccountProvider>("provider", Provider);
        }
    }
}
#pragma warning restore CS0618
