// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCustomerResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Contains created account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nexus.Casp.Client.Models.CreateAccountResponse>? Accounts { get; set; }
#nullable restore
#else
        public List<global::Nexus.Casp.Client.Models.CreateAccountResponse> Accounts { get; set; }
#endif
        /// <summary>Residental address of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>Number of the primary bank of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccount { get; set; }
#nullable restore
#else
        public string BankAccount { get; set; }
#endif
        /// <summary>Residental city of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>Name of the company of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>Country Code of this customer (ISO 4217)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>The date and time this customer is created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>Currency this Customer is allowed to transact in (ISO 4217)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Unique identifier for this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>Optional customer data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CreateCustomerResponse_data? Data { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CreateCustomerResponse_data Data { get; set; }
#endif
        /// <summary>Date of birth for this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateOfBirth { get; set; }
#nullable restore
#else
        public string DateOfBirth { get; set; }
#endif
        /// <summary>Email address for this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>External identifier of the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCustomerCode { get; set; }
#nullable restore
#else
        public string ExternalCustomerCode { get; set; }
#endif
        /// <summary>First name of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>dentified Name of the primary bank account of the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentifiedBankAccountName { get; set; }
#nullable restore
#else
        public string IdentifiedBankAccountName { get; set; }
#endif
        /// <summary>Customer is a business</summary>
        public bool? IsBusiness { get; set; }
        /// <summary>Indication of whether a review has been recommended on a customer or not</summary>
        public bool? IsReviewRecommended { get; set; }
        /// <summary>Last name of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Last date the customer was reviewed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestReview { get; set; }
#nullable restore
#else
        public string LatestReview { get; set; }
#endif
        /// <summary>Name of this customer. This is the name that will be checked against the sanctionlist in the portal if the feature is enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Phone number for this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Portfolio this customer belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PortFolioCode { get; set; }
#nullable restore
#else
        public string PortFolioCode { get; set; }
#endif
        /// <summary>Risk of a customer from a compliance and regulatory perspective:- `None` - Default- `Low`- `Medium`- `High`- `VeryHigh`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RiskQualification { get; set; }
#nullable restore
#else
        public string RiskQualification { get; set; }
#endif
        /// <summary>Residental state of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Status of Customer- `New` - Default- `Active`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Risklevel of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Trustlevel { get; set; }
#nullable restore
#else
        public string Trustlevel { get; set; }
#endif
        /// <summary>Residental zip code of this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZipCode { get; set; }
#nullable restore
#else
        public string ZipCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateCustomerResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CreateCustomerResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CreateCustomerResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts", n => { Accounts = n.GetCollectionOfObjectValues<global::Nexus.Casp.Client.Models.CreateAccountResponse>(global::Nexus.Casp.Client.Models.CreateAccountResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "address", n => { Address = n.GetStringValue(); } },
                { "bankAccount", n => { BankAccount = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "countryCode", n => { CountryCode = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Nexus.Casp.Client.Models.CreateCustomerResponse_data>(global::Nexus.Casp.Client.Models.CreateCustomerResponse_data.CreateFromDiscriminatorValue); } },
                { "dateOfBirth", n => { DateOfBirth = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "externalCustomerCode", n => { ExternalCustomerCode = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "identifiedBankAccountName", n => { IdentifiedBankAccountName = n.GetStringValue(); } },
                { "isBusiness", n => { IsBusiness = n.GetBoolValue(); } },
                { "isReviewRecommended", n => { IsReviewRecommended = n.GetBoolValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "latestReview", n => { LatestReview = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "portFolioCode", n => { PortFolioCode = n.GetStringValue(); } },
                { "riskQualification", n => { RiskQualification = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "trustlevel", n => { Trustlevel = n.GetStringValue(); } },
                { "zipCode", n => { ZipCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Nexus.Casp.Client.Models.CreateAccountResponse>("accounts", Accounts);
            writer.WriteStringValue("address", Address);
            writer.WriteStringValue("bankAccount", BankAccount);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteStringValue("countryCode", CountryCode);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CreateCustomerResponse_data>("data", Data);
            writer.WriteStringValue("dateOfBirth", DateOfBirth);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("externalCustomerCode", ExternalCustomerCode);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("identifiedBankAccountName", IdentifiedBankAccountName);
            writer.WriteBoolValue("isBusiness", IsBusiness);
            writer.WriteBoolValue("isReviewRecommended", IsReviewRecommended);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteStringValue("latestReview", LatestReview);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("portFolioCode", PortFolioCode);
            writer.WriteStringValue("riskQualification", RiskQualification);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("trustlevel", Trustlevel);
            writer.WriteStringValue("zipCode", ZipCode);
        }
    }
}
#pragma warning restore CS0618
