// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCustodianScheduleRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Code of the bucket of which the custodian balance will be calculated from.This balance is used to determine the payout amount using the Rate and RateType.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketCode { get; set; }
#nullable restore
#else
        public string BucketCode { get; set; }
#endif
        /// <summary>Code of the crypto currency which the transaction is processed in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Three letter code of the currency which the transaction is processed in (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Rate in decimals (relative value).0.01 equals 1%.</summary>
        public double? DefaultRate { get; set; }
        /// <summary>Code of the payment method which the transaction is processed with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodCode { get; set; }
#nullable restore
#else
        public string PaymentMethodCode { get; set; }
#endif
        /// <summary>Define the Interval the payouts will happen.A unit of `Days` with an amount of `7` means a weekly payout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.GetSchedulePayoutPeriodRecord? PayoutPeriod { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.GetSchedulePayoutPeriodRecord PayoutPeriod { get; set; }
#endif
        /// <summary>What rate algorithm to use for the interest calculation.</summary>
        public global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequestRateType? RateType { get; set; }
        /// <summary>When will this schedule start triggering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>Define the Interval on which the balances will be snapshotted.A unit of `Days` with an amount of `1` means that the balance will be determined on a daily basis.Different rates can be applied to these subintervals.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.GetScheduleSubIntervalPeriodRecord? SubIntervalPeriod { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.GetScheduleSubIntervalPeriodRecord SubIntervalPeriod { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bucketCode", n => { BucketCode = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "defaultRate", n => { DefaultRate = n.GetDoubleValue(); } },
                { "paymentMethodCode", n => { PaymentMethodCode = n.GetStringValue(); } },
                { "payoutPeriod", n => { PayoutPeriod = n.GetObjectValue<global::Nexus.Casp.Client.Models.GetSchedulePayoutPeriodRecord>(global::Nexus.Casp.Client.Models.GetSchedulePayoutPeriodRecord.CreateFromDiscriminatorValue); } },
                { "rateType", n => { RateType = n.GetEnumValue<global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequestRateType>(); } },
                { "startDate", n => { StartDate = n.GetStringValue(); } },
                { "subIntervalPeriod", n => { SubIntervalPeriod = n.GetObjectValue<global::Nexus.Casp.Client.Models.GetScheduleSubIntervalPeriodRecord>(global::Nexus.Casp.Client.Models.GetScheduleSubIntervalPeriodRecord.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bucketCode", BucketCode);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteDoubleValue("defaultRate", DefaultRate);
            writer.WriteStringValue("paymentMethodCode", PaymentMethodCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.GetSchedulePayoutPeriodRecord>("payoutPeriod", PayoutPeriod);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.CreateCustodianScheduleRequestRateType>("rateType", RateType);
            writer.WriteStringValue("startDate", StartDate);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.GetScheduleSubIntervalPeriodRecord>("subIntervalPeriod", SubIntervalPeriod);
        }
    }
}
#pragma warning restore CS0618
