// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateBuyCustodianTransactionResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Nexus generated unique identifier of the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountCode { get; set; }
#nullable restore
#else
        public string AccountCode { get; set; }
#endif
        /// <summary>Change in balance for the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.BalanceMutationResponse? BalanceMutation { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.BalanceMutationResponse BalanceMutation { get; set; }
#endif
        /// <summary>Resulting new transaction&apos;s data</summary>
        public double? BaseFiatAmountToPay { get; set; }
        /// <summary>Message sent as part of the transaction in the Blockchain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockchainMessage { get; set; }
#nullable restore
#else
        public string BlockchainMessage { get; set; }
#endif
        /// <summary>Id of the related Transaction in the Blockchain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockchainTransactionId { get; set; }
#nullable restore
#else
        public string BlockchainTransactionId { get; set; }
#endif
        /// <summary>Url to send callback notifications on status updates to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>Date and time this transaction was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>Crypto code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Currency code (ISO 4217)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Unique identifier of the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>Resulting new transaction&apos;s data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse_data? Data { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse_data Data { get; set; }
#endif
        /// <summary>Crypto address to which this transaction is sent out to (SENDOUT only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationCryptoAddress { get; set; }
#nullable restore
#else
        public string DestinationCryptoAddress { get; set; }
#endif
        /// <summary>Transaction sub type</summary>
        public global::Nexus.Casp.Client.Models.Direction? Direction { get; set; }
        /// <summary>Adjusted amounts executed by Nexus</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.AmountsResponse? ExecutedAmounts { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.AmountsResponse ExecutedAmounts { get; set; }
#endif
        /// <summary>Transaction fees</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.FeeResponse? Fees { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.FeeResponse Fees { get; set; }
#endif
        /// <summary>Resulting new transaction&apos;s data</summary>
        public double? FiatAmountToPay { get; set; }
        /// <summary>Unique identifier of the related transactionUsed for SendInternal and Swap</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedTransactionCode { get; set; }
#nullable restore
#else
        public string LinkedTransactionCode { get; set; }
#endif
        /// <summary>Unique identifier of the payment method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodCode { get; set; }
#nullable restore
#else
        public string PaymentMethodCode { get; set; }
#endif
        /// <summary>Optional payment reference associated with this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReference { get; set; }
#nullable restore
#else
        public string PaymentReference { get; set; }
#endif
        /// <summary>Original requested amounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.AmountsResponse? RequestedAmounts { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.AmountsResponse RequestedAmounts { get; set; }
#endif
        /// <summary>Transaction status</summary>
        public global::Nexus.Casp.Client.Models.CustodianTransactionStatus? Status { get; set; }
        /// <summary>Margin made from Swap transactions in crypto</summary>
        public double? SwapMarginAmountCrypto { get; set; }
        /// <summary>Unique identifier of the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionCode { get; set; }
#nullable restore
#else
        public string TransactionCode { get; set; }
#endif
        /// <summary>Transaction type</summary>
        public global::Nexus.Casp.Client.Models.TransactionTypes? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCode", n => { AccountCode = n.GetStringValue(); } },
                { "balanceMutation", n => { BalanceMutation = n.GetObjectValue<global::Nexus.Casp.Client.Models.BalanceMutationResponse>(global::Nexus.Casp.Client.Models.BalanceMutationResponse.CreateFromDiscriminatorValue); } },
                { "baseFiatAmountToPay", n => { BaseFiatAmountToPay = n.GetDoubleValue(); } },
                { "blockchainMessage", n => { BlockchainMessage = n.GetStringValue(); } },
                { "blockchainTransactionId", n => { BlockchainTransactionId = n.GetStringValue(); } },
                { "callbackUrl", n => { CallbackUrl = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse_data>(global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse_data.CreateFromDiscriminatorValue); } },
                { "destinationCryptoAddress", n => { DestinationCryptoAddress = n.GetStringValue(); } },
                { "direction", n => { Direction = n.GetEnumValue<global::Nexus.Casp.Client.Models.Direction>(); } },
                { "executedAmounts", n => { ExecutedAmounts = n.GetObjectValue<global::Nexus.Casp.Client.Models.AmountsResponse>(global::Nexus.Casp.Client.Models.AmountsResponse.CreateFromDiscriminatorValue); } },
                { "fees", n => { Fees = n.GetObjectValue<global::Nexus.Casp.Client.Models.FeeResponse>(global::Nexus.Casp.Client.Models.FeeResponse.CreateFromDiscriminatorValue); } },
                { "fiatAmountToPay", n => { FiatAmountToPay = n.GetDoubleValue(); } },
                { "linkedTransactionCode", n => { LinkedTransactionCode = n.GetStringValue(); } },
                { "paymentMethodCode", n => { PaymentMethodCode = n.GetStringValue(); } },
                { "paymentReference", n => { PaymentReference = n.GetStringValue(); } },
                { "requestedAmounts", n => { RequestedAmounts = n.GetObjectValue<global::Nexus.Casp.Client.Models.AmountsResponse>(global::Nexus.Casp.Client.Models.AmountsResponse.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Nexus.Casp.Client.Models.CustodianTransactionStatus>(); } },
                { "swapMarginAmountCrypto", n => { SwapMarginAmountCrypto = n.GetDoubleValue(); } },
                { "transactionCode", n => { TransactionCode = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Nexus.Casp.Client.Models.TransactionTypes>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountCode", AccountCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.BalanceMutationResponse>("balanceMutation", BalanceMutation);
            writer.WriteDoubleValue("baseFiatAmountToPay", BaseFiatAmountToPay);
            writer.WriteStringValue("blockchainMessage", BlockchainMessage);
            writer.WriteStringValue("blockchainTransactionId", BlockchainTransactionId);
            writer.WriteStringValue("callbackUrl", CallbackUrl);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CreateBuyCustodianTransactionResponse_data>("data", Data);
            writer.WriteStringValue("destinationCryptoAddress", DestinationCryptoAddress);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.Direction>("direction", Direction);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.AmountsResponse>("executedAmounts", ExecutedAmounts);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.FeeResponse>("fees", Fees);
            writer.WriteDoubleValue("fiatAmountToPay", FiatAmountToPay);
            writer.WriteStringValue("linkedTransactionCode", LinkedTransactionCode);
            writer.WriteStringValue("paymentMethodCode", PaymentMethodCode);
            writer.WriteStringValue("paymentReference", PaymentReference);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.AmountsResponse>("requestedAmounts", RequestedAmounts);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.CustodianTransactionStatus>("status", Status);
            writer.WriteDoubleValue("swapMarginAmountCrypto", SwapMarginAmountCrypto);
            writer.WriteStringValue("transactionCode", TransactionCode);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.TransactionTypes>("type", Type);
        }
    }
}
#pragma warning restore CS0618
