// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>What rate algorithm to use for the interest calculation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateCustodianScheduleRequestRateType
    {
        [EnumMember(Value = "WeeklyAPY")]
        #pragma warning disable CS1591
        WeeklyAPY,
        #pragma warning restore CS1591
    }
}
