// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrencyReserveItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Total amount - Locked amount</summary>
        public decimal? Available { get; set; }
        /// <summary>Bucket unique identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketCode { get; set; }
#nullable restore
#else
        public string BucketCode { get; set; }
#endif
        /// <summary>Reserve unique identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Exchange unique identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeCode { get; set; }
#nullable restore
#else
        public string ExchangeCode { get; set; }
#endif
        /// <summary>Reserve is active</summary>
        public bool? IsActive { get; set; }
        /// <summary>Locked amount which are not available to use</summary>
        public decimal? Locked { get; set; }
        /// <summary>Reserve name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Total amount</summary>
        public decimal? Total { get; set; }
        /// <summary>Reserve type- `Exchange`- `Yield`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Unconfirmed fiat deposits</summary>
        public decimal? Unconfirmed { get; set; }
        /// <summary>DateTime of last update</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Updated { get; set; }
#nullable restore
#else
        public string Updated { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CurrencyReserveItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CurrencyReserveItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CurrencyReserveItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available", n => { Available = n.GetDecimalValue(); } },
                { "bucketCode", n => { BucketCode = n.GetStringValue(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "exchangeCode", n => { ExchangeCode = n.GetStringValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "locked", n => { Locked = n.GetDecimalValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "total", n => { Total = n.GetDecimalValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "unconfirmed", n => { Unconfirmed = n.GetDecimalValue(); } },
                { "updated", n => { Updated = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("available", Available);
            writer.WriteStringValue("bucketCode", BucketCode);
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("exchangeCode", ExchangeCode);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteDecimalValue("locked", Locked);
            writer.WriteStringValue("name", Name);
            writer.WriteDecimalValue("total", Total);
            writer.WriteStringValue("type", Type);
            writer.WriteDecimalValue("unconfirmed", Unconfirmed);
            writer.WriteStringValue("updated", Updated);
        }
    }
}
#pragma warning restore CS0618
