// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrencyResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Base currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.BaseCurrency? BaseCurrency { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.BaseCurrency BaseCurrency { get; set; }
#endif
        /// <summary>List of available currencies and their rates from the base currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nexus.Casp.Client.Models.Currency>? Currencies { get; set; }
#nullable restore
#else
        public List<global::Nexus.Casp.Client.Models.Currency> Currencies { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CurrencyResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CurrencyResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CurrencyResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseCurrency", n => { BaseCurrency = n.GetObjectValue<global::Nexus.Casp.Client.Models.BaseCurrency>(global::Nexus.Casp.Client.Models.BaseCurrency.CreateFromDiscriminatorValue); } },
                { "currencies", n => { Currencies = n.GetCollectionOfObjectValues<global::Nexus.Casp.Client.Models.Currency>(global::Nexus.Casp.Client.Models.Currency.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.BaseCurrency>("baseCurrency", BaseCurrency);
            writer.WriteCollectionOfObjectValues<global::Nexus.Casp.Client.Models.Currency>("currencies", Currencies);
        }
    }
}
#pragma warning restore CS0618
