// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerBankAccountRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Bank of the customer&apos;s bank account. This is used to link or create a bank to the customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CustomerBankRequest? Bank { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CustomerBankRequest Bank { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 . _ @ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountNumber { get; set; }
#nullable restore
#else
        public string BankAccountNumber { get; set; }
#endif
        /// <summary>Must be exactly 3 uppercase letters (A-Z). Example: EUR</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Identified Name for a customer&apos;s Bank account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentifiedBankAccountName { get; set; }
#nullable restore
#else
        public string IdentifiedBankAccountName { get; set; }
#endif
        /// <summary>Indicates the primary account of a customer. Setting this true, will set the other bank accounts of a customer to false. Default is true.</summary>
        public bool? IsPrimary { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustomerBankAccountRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustomerBankAccountRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustomerBankAccountRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bank", n => { Bank = n.GetObjectValue<global::Nexus.Casp.Client.Models.CustomerBankRequest>(global::Nexus.Casp.Client.Models.CustomerBankRequest.CreateFromDiscriminatorValue); } },
                { "bankAccountNumber", n => { BankAccountNumber = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "identifiedBankAccountName", n => { IdentifiedBankAccountName = n.GetStringValue(); } },
                { "isPrimary", n => { IsPrimary = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CustomerBankRequest>("bank", Bank);
            writer.WriteStringValue("bankAccountNumber", BankAccountNumber);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("identifiedBankAccountName", IdentifiedBankAccountName);
            writer.WriteBoolValue("isPrimary", IsPrimary);
        }
    }
}
#pragma warning restore CS0618
