// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustodianTransactionNotificationCallbackResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The count of the callbacks sent</summary>
        public int? DequeueCount { get; set; }
        /// <summary>The timestamp when the notification was finished</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Finished { get; set; }
#nullable restore
#else
        public string Finished { get; set; }
#endif
        /// <summary>The timestamp when the notification was inserted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inserted { get; set; }
#nullable restore
#else
        public string Inserted { get; set; }
#endif
        /// <summary>Tells if the callback is successfull</summary>
        public bool? IsSuccess { get; set; }
        /// <summary>Unique identifier of the partner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LabelPartnerCode { get; set; }
#nullable restore
#else
        public string LabelPartnerCode { get; set; }
#endif
        /// <summary>The notification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CustodianLabelNotificationResponse? Notification { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CustodianLabelNotificationResponse Notification { get; set; }
#endif
        /// <summary>Unique identifier of the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionCode { get; set; }
#nullable restore
#else
        public string TransactionCode { get; set; }
#endif
        /// <summary>Url of the callback. The maximum length is 256 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustodianTransactionNotificationCallbackResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustodianTransactionNotificationCallbackResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustodianTransactionNotificationCallbackResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dequeueCount", n => { DequeueCount = n.GetIntValue(); } },
                { "finished", n => { Finished = n.GetStringValue(); } },
                { "inserted", n => { Inserted = n.GetStringValue(); } },
                { "isSuccess", n => { IsSuccess = n.GetBoolValue(); } },
                { "labelPartnerCode", n => { LabelPartnerCode = n.GetStringValue(); } },
                { "notification", n => { Notification = n.GetObjectValue<global::Nexus.Casp.Client.Models.CustodianLabelNotificationResponse>(global::Nexus.Casp.Client.Models.CustodianLabelNotificationResponse.CreateFromDiscriminatorValue); } },
                { "transactionCode", n => { TransactionCode = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("dequeueCount", DequeueCount);
            writer.WriteStringValue("finished", Finished);
            writer.WriteStringValue("inserted", Inserted);
            writer.WriteBoolValue("isSuccess", IsSuccess);
            writer.WriteStringValue("labelPartnerCode", LabelPartnerCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CustodianLabelNotificationResponse>("notification", Notification);
            writer.WriteStringValue("transactionCode", TransactionCode);
            writer.WriteStringValue("url", Url);
        }
    }
}
#pragma warning restore CS0618
