// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerPersonTypeDTO
    {
        [EnumMember(Value = "Director")]
        #pragma warning disable CS1591
        Director,
        #pragma warning restore CS1591
        [EnumMember(Value = "UltimateBeneficialOwner")]
        #pragma warning disable CS1591
        UltimateBeneficialOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "PseudoUltimateBeneficialOwner")]
        #pragma warning disable CS1591
        PseudoUltimateBeneficialOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorisedRepresentative")]
        #pragma warning disable CS1591
        AuthorisedRepresentative,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
