// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustodianLabelNotificationTxMerchantResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Crypto Payment Address of the merchant transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoPaymentAddress { get; set; }
#nullable restore
#else
        public string CryptoPaymentAddress { get; set; }
#endif
        /// <summary>Crypto Payment Uri of the merchant transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoPaymentUri { get; set; }
#nullable restore
#else
        public string CryptoPaymentUri { get; set; }
#endif
        /// <summary>Currency amount of the merchant transaction</summary>
        public double? CurrencyAmount { get; set; }
        /// <summary>Expected crypto amount of the merchant transaction</summary>
        public double? ExpectedCryptoAmount { get; set; }
        /// <summary>Customer email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantCustomerEmailAddress { get; set; }
#nullable restore
#else
        public string MerchantCustomerEmailAddress { get; set; }
#endif
        /// <summary>Payment Reference of the merchant transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReference { get; set; }
#nullable restore
#else
        public string PaymentReference { get; set; }
#endif
        /// <summary>Unique id of the merchant transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceiveCryptoTxId { get; set; }
#nullable restore
#else
        public string ReceiveCryptoTxId { get; set; }
#endif
        /// <summary>Received Crypto amount of the merchant transaction</summary>
        public double? ReceivedCryptoAmount { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustodianLabelNotificationTxMerchantResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustodianLabelNotificationTxMerchantResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustodianLabelNotificationTxMerchantResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cryptoPaymentAddress", n => { CryptoPaymentAddress = n.GetStringValue(); } },
                { "cryptoPaymentUri", n => { CryptoPaymentUri = n.GetStringValue(); } },
                { "currencyAmount", n => { CurrencyAmount = n.GetDoubleValue(); } },
                { "expectedCryptoAmount", n => { ExpectedCryptoAmount = n.GetDoubleValue(); } },
                { "merchantCustomerEmailAddress", n => { MerchantCustomerEmailAddress = n.GetStringValue(); } },
                { "paymentReference", n => { PaymentReference = n.GetStringValue(); } },
                { "receiveCryptoTxId", n => { ReceiveCryptoTxId = n.GetStringValue(); } },
                { "receivedCryptoAmount", n => { ReceivedCryptoAmount = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cryptoPaymentAddress", CryptoPaymentAddress);
            writer.WriteStringValue("cryptoPaymentUri", CryptoPaymentUri);
            writer.WriteDoubleValue("currencyAmount", CurrencyAmount);
            writer.WriteDoubleValue("expectedCryptoAmount", ExpectedCryptoAmount);
            writer.WriteStringValue("merchantCustomerEmailAddress", MerchantCustomerEmailAddress);
            writer.WriteStringValue("paymentReference", PaymentReference);
            writer.WriteStringValue("receiveCryptoTxId", ReceiveCryptoTxId);
            writer.WriteDoubleValue("receivedCryptoAmount", ReceivedCryptoAmount);
        }
    }
}
#pragma warning restore CS0618
