// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>Transaction status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustodianTransactionStatus
    {
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "Confirming")]
        #pragma warning disable CS1591
        Confirming,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sending")]
        #pragma warning disable CS1591
        Sending,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIMULATED")]
        #pragma warning disable CS1591
        SIMULATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BLOCKED")]
        #pragma warning disable CS1591
        BLOCKED,
        #pragma warning restore CS1591
        [EnumMember(Value = "Staged")]
        #pragma warning disable CS1591
        Staged,
        #pragma warning restore CS1591
        [EnumMember(Value = "ToCancel")]
        #pragma warning disable CS1591
        ToCancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Initiated")]
        #pragma warning disable CS1591
        Initiated,
        #pragma warning restore CS1591
        [EnumMember(Value = "ToPayout")]
        #pragma warning disable CS1591
        ToPayout,
        #pragma warning restore CS1591
        [EnumMember(Value = "PayoutConfirming")]
        #pragma warning disable CS1591
        PayoutConfirming,
        #pragma warning restore CS1591
    }
}
