// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerBankRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankBicCode { get; set; }
#nullable restore
#else
        public string BankBicCode { get; set; }
#endif
        /// <summary>Bank city of the customer&apos;s bank account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankCity { get; set; }
#nullable restore
#else
        public string BankCity { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankCountryCode { get; set; }
#nullable restore
#else
        public string BankCountryCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankIBANCode { get; set; }
#nullable restore
#else
        public string BankIBANCode { get; set; }
#endif
        /// <summary>Bank name of the customer&apos;s bank account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankName { get; set; }
#nullable restore
#else
        public string BankName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustomerBankRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustomerBankRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustomerBankRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankBicCode", n => { BankBicCode = n.GetStringValue(); } },
                { "bankCity", n => { BankCity = n.GetStringValue(); } },
                { "bankCountryCode", n => { BankCountryCode = n.GetStringValue(); } },
                { "bankIBANCode", n => { BankIBANCode = n.GetStringValue(); } },
                { "bankName", n => { BankName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bankBicCode", BankBicCode);
            writer.WriteStringValue("bankCity", BankCity);
            writer.WriteStringValue("bankCountryCode", BankCountryCode);
            writer.WriteStringValue("bankIBANCode", BankIBANCode);
            writer.WriteStringValue("bankName", BankName);
        }
    }
}
#pragma warning restore CS0618
