// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustodianClawbackRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Nexus generated unique identifier of the account or combination of crypto code and address.Example: XLM-14DuxbRVYPSmt1c3f2UnoKVUHkR5bVB9oa</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountCode { get; set; }
#nullable restore
#else
        public string AccountCode { get; set; }
#endif
        /// <summary>The amount of cryptocurrency the transaction should be created for.</summary>
        public decimal? CryptoAmount { get; set; }
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Must be exactly 3 uppercase letters (A-Z). Example: EUR</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>Optional user defined data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CustodianClawbackRequest_data? Data { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CustodianClawbackRequest_data Data { get; set; }
#endif
        /// <summary>Optional payment reference to associate with this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReference { get; set; }
#nullable restore
#else
        public string PaymentReference { get; set; }
#endif
        /// <summary>The optional SELL price at which the cryptocurrency will be sold.**Please note** the fixed price is subject to some benchmarks configurable on the select payment method.Default ranges:- 5% price increase allowed- 10% price reduction allowedSince a custodian clawback transaction does not affect the fiat balance of a customer, this is purely to calculate possible fees.</summary>
        public decimal? RequestedPrice { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustodianClawbackRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustodianClawbackRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustodianClawbackRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCode", n => { AccountCode = n.GetStringValue(); } },
                { "cryptoAmount", n => { CryptoAmount = n.GetDecimalValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Nexus.Casp.Client.Models.CustodianClawbackRequest_data>(global::Nexus.Casp.Client.Models.CustodianClawbackRequest_data.CreateFromDiscriminatorValue); } },
                { "paymentReference", n => { PaymentReference = n.GetStringValue(); } },
                { "requestedPrice", n => { RequestedPrice = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountCode", AccountCode);
            writer.WriteDecimalValue("cryptoAmount", CryptoAmount);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CustodianClawbackRequest_data>("data", Data);
            writer.WriteStringValue("paymentReference", PaymentReference);
            writer.WriteDecimalValue("requestedPrice", RequestedPrice);
        }
    }
}
#pragma warning restore CS0618
