// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustodianPaymentRequestResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A payment string that can be represented as a QR Code to be scanned by the sender</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentUri { get; set; }
#nullable restore
#else
        public string PaymentUri { get; set; }
#endif
        /// <summary>New transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CreateCustodianTransactionResponse? Transaction { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CreateCustodianTransactionResponse Transaction { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CustodianPaymentRequestResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.CustodianPaymentRequestResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.CustodianPaymentRequestResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "paymentUri", n => { PaymentUri = n.GetStringValue(); } },
                { "transaction", n => { Transaction = n.GetObjectValue<global::Nexus.Casp.Client.Models.CreateCustodianTransactionResponse>(global::Nexus.Casp.Client.Models.CreateCustodianTransactionResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("paymentUri", PaymentUri);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CreateCustodianTransactionResponse>("transaction", Transaction);
        }
    }
}
#pragma warning restore CS0618
