// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Direction
    {
        [EnumMember(Value = "SOURCE")]
        #pragma warning disable CS1591
        SOURCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESTINATION")]
        #pragma warning disable CS1591
        DESTINATION,
        #pragma warning restore CS1591
    }
}
