// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DocumentStoreRecordResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>An optional alias specified for the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The date and time the file was uploadedExample: 2018-10-21T13:28:06Z</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedOn { get; set; }
#nullable restore
#else
        public string CreatedOn { get; set; }
#endif
        /// <summary>The Customer code used to identify the customer associated with the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>An optional description specified for the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The document type associated with the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.DocumentStoreTypeInfo? DocumentStoreType { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.DocumentStoreTypeInfo DocumentStoreType { get; set; }
#endif
        /// <summary>Name of the file in the Document Store</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The full path of the file in the Document Store</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>The size of the file in megabytes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileSizeInMB { get; set; }
#nullable restore
#else
        public string FileSizeInMB { get; set; }
#endif
        /// <summary>An optional external unique identifier for the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemReference { get; set; }
#nullable restore
#else
        public string ItemReference { get; set; }
#endif
        /// <summary>The state of the file in the Document StorePossible states are:- Active- Deleted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The date and time the file was last updatedExample: 2018-10-21T13:28:06Z</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedOn { get; set; }
#nullable restore
#else
        public string UpdatedOn { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.DocumentStoreRecordResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.DocumentStoreRecordResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.DocumentStoreRecordResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "createdOn", n => { CreatedOn = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "documentStoreType", n => { DocumentStoreType = n.GetObjectValue<global::Nexus.Casp.Client.Models.DocumentStoreTypeInfo>(global::Nexus.Casp.Client.Models.DocumentStoreTypeInfo.CreateFromDiscriminatorValue); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "filePath", n => { FilePath = n.GetStringValue(); } },
                { "fileSizeInMB", n => { FileSizeInMB = n.GetStringValue(); } },
                { "itemReference", n => { ItemReference = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "updatedOn", n => { UpdatedOn = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteStringValue("createdOn", CreatedOn);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.DocumentStoreTypeInfo>("documentStoreType", DocumentStoreType);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteStringValue("filePath", FilePath);
            writer.WriteStringValue("fileSizeInMB", FileSizeInMB);
            writer.WriteStringValue("itemReference", ItemReference);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("updatedOn", UpdatedOn);
        }
    }
}
#pragma warning restore CS0618
