// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldsToClearEnum
    {
        [EnumMember(Value = "Name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bank")]
        #pragma warning disable CS1591
        Bank,
        #pragma warning restore CS1591
    }
}
