// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FileUpdateData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Can only contain standard keyboard characters (letters, digits, punctuation, and spaces)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>Can only contain standard keyboard characters (letters, digits, punctuation, and spaces)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentStoreTypeCode { get; set; }
#nullable restore
#else
        public string DocumentStoreTypeCode { get; set; }
#endif
        /// <summary>The path of the file in the Document Store in the following format: ```path/to/file.txt```- Use single forward slashes (/) as path separators- Do not include leading slashes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>Can only contain standard keyboard characters (letters, digits, punctuation, and spaces)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemReference { get; set; }
#nullable restore
#else
        public string ItemReference { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.FileUpdateData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.FileUpdateData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.FileUpdateData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "documentStoreTypeCode", n => { DocumentStoreTypeCode = n.GetStringValue(); } },
                { "filePath", n => { FilePath = n.GetStringValue(); } },
                { "itemReference", n => { ItemReference = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("documentStoreTypeCode", DocumentStoreTypeCode);
            writer.WriteStringValue("filePath", FilePath);
            writer.WriteStringValue("itemReference", ItemReference);
        }
    }
}
#pragma warning restore CS0618
