// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetCryptoAddressResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Address of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>Reference that is used to create the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressReference { get; set; }
#nullable restore
#else
        public string AddressReference { get; set; }
#endif
        /// <summary>Comment added by the user while creating the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>Created date of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>User who created the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Crypto code of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Exchange wallet code of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeWalletCode { get; set; }
#nullable restore
#else
        public string ExchangeWalletCode { get; set; }
#endif
        /// <summary>Description of the sink of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.SinkDetails? Sink { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.SinkDetails Sink { get; set; }
#endif
        /// <summary>Description of the source of the crypto address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.SourceDetails? Source { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.SourceDetails Source { get; set; }
#endif
        /// <summary>Status(es) of the crypto address- `Inactive`- `Active`- `Deleted`- `Whitelisted`- `NotValidated`- `ToBeDeleted`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Status { get; set; }
#nullable restore
#else
        public List<string> Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetCryptoAddressResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.GetCryptoAddressResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.GetCryptoAddressResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "addressReference", n => { AddressReference = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "exchangeWalletCode", n => { ExchangeWalletCode = n.GetStringValue(); } },
                { "sink", n => { Sink = n.GetObjectValue<global::Nexus.Casp.Client.Models.SinkDetails>(global::Nexus.Casp.Client.Models.SinkDetails.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetObjectValue<global::Nexus.Casp.Client.Models.SourceDetails>(global::Nexus.Casp.Client.Models.SourceDetails.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteStringValue("addressReference", AddressReference);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("exchangeWalletCode", ExchangeWalletCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.SinkDetails>("sink", Sink);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.SourceDetails>("source", Source);
            writer.WriteCollectionOfPrimitiveValues<string>("status", Status);
        }
    }
}
#pragma warning restore CS0618
