// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetCustomerComplianceHistoryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The date and time the customer&apos;s compliance history record was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>Currency this Customer is allowed to transact in (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Unique identifier for this customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>By whom was the customer&apos;s compliance history record created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitiatedBy { get; set; }
#nullable restore
#else
        public string InitiatedBy { get; set; }
#endif
        /// <summary>Customer is a business.</summary>
        public bool? IsBusiness { get; set; }
        /// <summary>Indication of whether a review has been recommended on a customer or not.</summary>
        public bool? IsReviewRecommended { get; set; }
        /// <summary>Last date the customer was reviewed (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestReview { get; set; }
#nullable restore
#else
        public string LatestReview { get; set; }
#endif
        /// <summary>The optional reason why the customer&apos;s compliance history record was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Risk of a customer from a compliance and regulatory perspective:- `None` - Default- `Low`- `Medium`- `High`- `VeryHigh`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RiskQualification { get; set; }
#nullable restore
#else
        public string RiskQualification { get; set; }
#endif
        /// <summary>Status of customer:- `New`- `Active`- `Deleted`- `UnderReview`- `Blocked`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Risklevel of this customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Trustlevel { get; set; }
#nullable restore
#else
        public string Trustlevel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetCustomerComplianceHistoryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.GetCustomerComplianceHistoryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.GetCustomerComplianceHistoryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
                { "initiatedBy", n => { InitiatedBy = n.GetStringValue(); } },
                { "isBusiness", n => { IsBusiness = n.GetBoolValue(); } },
                { "isReviewRecommended", n => { IsReviewRecommended = n.GetBoolValue(); } },
                { "latestReview", n => { LatestReview = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "riskQualification", n => { RiskQualification = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "trustlevel", n => { Trustlevel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
            writer.WriteStringValue("initiatedBy", InitiatedBy);
            writer.WriteBoolValue("isBusiness", IsBusiness);
            writer.WriteBoolValue("isReviewRecommended", IsReviewRecommended);
            writer.WriteStringValue("latestReview", LatestReview);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("riskQualification", RiskQualification);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("trustlevel", Trustlevel);
        }
    }
}
#pragma warning restore CS0618
