// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrderPagedResult : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The filteringParameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.GetOrderPagedResult_filteringParameters? FilteringParameters { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.GetOrderPagedResult_filteringParameters FilteringParameters { get; set; }
#endif
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nexus.Casp.Client.Models.GetOrder>? Records { get; set; }
#nullable restore
#else
        public List<global::Nexus.Casp.Client.Models.GetOrder> Records { get; set; }
#endif
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetOrderPagedResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.GetOrderPagedResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.GetOrderPagedResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filteringParameters", n => { FilteringParameters = n.GetObjectValue<global::Nexus.Casp.Client.Models.GetOrderPagedResult_filteringParameters>(global::Nexus.Casp.Client.Models.GetOrderPagedResult_filteringParameters.CreateFromDiscriminatorValue); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::Nexus.Casp.Client.Models.GetOrder>(global::Nexus.Casp.Client.Models.GetOrder.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.GetOrderPagedResult_filteringParameters>("filteringParameters", FilteringParameters);
            writer.WriteIntValue("page", Page);
            writer.WriteCollectionOfObjectValues<global::Nexus.Casp.Client.Models.GetOrder>("records", Records);
            writer.WriteIntValue("total", Total);
            writer.WriteIntValue("totalPages", TotalPages);
        }
    }
}
#pragma warning restore CS0618
