// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrderExecuted : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Amount in crypto that is executed on the Exchange</summary>
        public decimal? Amount { get; set; }
        /// <summary>Fee paid for the order on the exchange in FIAT currency</summary>
        public decimal? Fee { get; set; }
        /// <summary>Is true when the requested amount does not match the executed amount.Meaning that the order was partially filled.</summary>
        public bool? Partial { get; set; }
        /// <summary>Price of the executed order</summary>
        public decimal? Price { get; set; }
        /// <summary>Total value of the executed order</summary>
        public decimal? Value { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetOrderExecuted"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.GetOrderExecuted CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.GetOrderExecuted();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDecimalValue(); } },
                { "fee", n => { Fee = n.GetDecimalValue(); } },
                { "partial", n => { Partial = n.GetBoolValue(); } },
                { "price", n => { Price = n.GetDecimalValue(); } },
                { "value", n => { Value = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("amount", Amount);
            writer.WriteDecimalValue("fee", Fee);
            writer.WriteBoolValue("partial", Partial);
            writer.WriteDecimalValue("price", Price);
            writer.WriteDecimalValue("value", Value);
        }
    }
}
#pragma warning restore CS0618
