// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetTransfer : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.GetTransferAddress? Address { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.GetTransferAddress Address { get; set; }
#endif
        /// <summary>Transfer&apos;s amount in crypto.</summary>
        public decimal? Amount { get; set; }
        /// <summary>Additional information provided by the transfer&apos;s creator as a comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>DateTime when this Transfer was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>Crypto of the transfer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>The unique identifier of the transfer in the exchange.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeTransferCode { get; set; }
#nullable restore
#else
        public string ExchangeTransferCode { get; set; }
#endif
        /// <summary>DateTime when the Transfer was finished.This includes cancellations and other error statuses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Finished { get; set; }
#nullable restore
#else
        public string Finished { get; set; }
#endif
        /// <summary>Internal reference price at creation time.</summary>
        public decimal? Price { get; set; }
        /// <summary>Status of the transfer.</summary>
        public global::Nexus.Casp.Client.Models.GetTransferStatus? Status { get; set; }
        /// <summary>Transfer&apos;s unique identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransferCode { get; set; }
#nullable restore
#else
        public string TransferCode { get; set; }
#endif
        /// <summary>Unique transaction id of the transfer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TxId { get; set; }
#nullable restore
#else
        public string TxId { get; set; }
#endif
        /// <summary>Type of transfer.</summary>
        public global::Nexus.Casp.Client.Models.GetTransferType? Type { get; set; }
        /// <summary>UserName of the transfer&apos;s creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetTransfer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.GetTransfer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.GetTransfer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Nexus.Casp.Client.Models.GetTransferAddress>(global::Nexus.Casp.Client.Models.GetTransferAddress.CreateFromDiscriminatorValue); } },
                { "amount", n => { Amount = n.GetDecimalValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "exchangeTransferCode", n => { ExchangeTransferCode = n.GetStringValue(); } },
                { "finished", n => { Finished = n.GetStringValue(); } },
                { "price", n => { Price = n.GetDecimalValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Nexus.Casp.Client.Models.GetTransferStatus>(); } },
                { "transferCode", n => { TransferCode = n.GetStringValue(); } },
                { "txId", n => { TxId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Nexus.Casp.Client.Models.GetTransferType>(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.GetTransferAddress>("address", Address);
            writer.WriteDecimalValue("amount", Amount);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("exchangeTransferCode", ExchangeTransferCode);
            writer.WriteStringValue("finished", Finished);
            writer.WriteDecimalValue("price", Price);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.GetTransferStatus>("status", Status);
            writer.WriteStringValue("transferCode", TransferCode);
            writer.WriteStringValue("txId", TxId);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.GetTransferType>("type", Type);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
