// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>Defines the flow of cryptos when selling.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HotWalletReceiveFlowTypeDTO
    {
        [EnumMember(Value = "MultiAddressFlow")]
        #pragma warning disable CS1591
        MultiAddressFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "SingleAddressUsingMemoFlow")]
        #pragma warning disable CS1591
        SingleAddressUsingMemoFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "MultiAddressWithForwardingToMainAddressFlow")]
        #pragma warning disable CS1591
        MultiAddressWithForwardingToMainAddressFlow,
        #pragma warning restore CS1591
    }
}
