// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LabelPartnerDigitalCurrencyAddressTypeDTO
    {
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "Exchange")]
        #pragma warning disable CS1591
        Exchange,
        #pragma warning restore CS1591
        [EnumMember(Value = "Coldstore")]
        #pragma warning disable CS1591
        Coldstore,
        #pragma warning restore CS1591
        [EnumMember(Value = "HotWallet")]
        #pragma warning disable CS1591
        HotWallet,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "Yield")]
        #pragma warning disable CS1591
        Yield,
        #pragma warning restore CS1591
    }
}
