// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LabelNotificationResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountCode { get; set; }
#nullable restore
#else
        public string AccountCode { get; set; }
#endif
        /// <summary>The buy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse? Buy { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse Buy { get; set; }
#endif
        /// <summary>The confirmations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationConfirmationResponse? Confirmations { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationConfirmationResponse Confirmations { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The cryptoCurrencyCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCurrencyCode { get; set; }
#nullable restore
#else
        public string CryptoCurrencyCode { get; set; }
#endif
        /// <summary>Unique identifier of the currency (ISO 4217)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The customerReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerReference { get; set; }
#nullable restore
#else
        public string CustomerReference { get; set; }
#endif
        /// <summary>The merchant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationTxMerchantResponse? Merchant { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationTxMerchantResponse Merchant { get; set; }
#endif
        /// <summary>The paymentMethodCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodCode { get; set; }
#nullable restore
#else
        public string PaymentMethodCode { get; set; }
#endif
        /// <summary>The receiveIn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationTxReceiveInResponse? ReceiveIn { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationTxReceiveInResponse ReceiveIn { get; set; }
#endif
        /// <summary>The sell property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationTxSellResponse? Sell { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationTxSellResponse Sell { get; set; }
#endif
        /// <summary>The sendout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.LabelNotificationTxSendoutResponse? Sendout { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.LabelNotificationTxSendoutResponse Sendout { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The transactionCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionCode { get; set; }
#nullable restore
#else
        public string TransactionCode { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The validUntil property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidUntil { get; set; }
#nullable restore
#else
        public string ValidUntil { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.LabelNotificationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.LabelNotificationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.LabelNotificationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCode", n => { AccountCode = n.GetStringValue(); } },
                { "buy", n => { Buy = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse>(global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse.CreateFromDiscriminatorValue); } },
                { "confirmations", n => { Confirmations = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationConfirmationResponse>(global::Nexus.Casp.Client.Models.LabelNotificationConfirmationResponse.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "cryptoCurrencyCode", n => { CryptoCurrencyCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerReference", n => { CustomerReference = n.GetStringValue(); } },
                { "merchant", n => { Merchant = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxMerchantResponse>(global::Nexus.Casp.Client.Models.LabelNotificationTxMerchantResponse.CreateFromDiscriminatorValue); } },
                { "paymentMethodCode", n => { PaymentMethodCode = n.GetStringValue(); } },
                { "receiveIn", n => { ReceiveIn = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxReceiveInResponse>(global::Nexus.Casp.Client.Models.LabelNotificationTxReceiveInResponse.CreateFromDiscriminatorValue); } },
                { "sell", n => { Sell = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxSellResponse>(global::Nexus.Casp.Client.Models.LabelNotificationTxSellResponse.CreateFromDiscriminatorValue); } },
                { "sendout", n => { Sendout = n.GetObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxSendoutResponse>(global::Nexus.Casp.Client.Models.LabelNotificationTxSendoutResponse.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "transactionCode", n => { TransactionCode = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "validUntil", n => { ValidUntil = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountCode", AccountCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse>("buy", Buy);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationConfirmationResponse>("confirmations", Confirmations);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("cryptoCurrencyCode", CryptoCurrencyCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerReference", CustomerReference);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxMerchantResponse>("merchant", Merchant);
            writer.WriteStringValue("paymentMethodCode", PaymentMethodCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxReceiveInResponse>("receiveIn", ReceiveIn);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxSellResponse>("sell", Sell);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.LabelNotificationTxSendoutResponse>("sendout", Sendout);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("transactionCode", TransactionCode);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("validUntil", ValidUntil);
        }
    }
}
#pragma warning restore CS0618
