// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LabelPartnerCryptoCurrency : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Blockchain on which we execute actions on for this LabelPartner crypto currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.Blockchain? Blockchain { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.Blockchain Blockchain { get; set; }
#endif
        /// <summary>Code of LabelPartner crypto currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Defines the flow of cryptos when selling.</summary>
        public global::Nexus.Casp.Client.Models.HotWalletReceiveFlowTypeDTO? HotWalletReceiveFlow { get; set; }
        /// <summary>States whether the LabelPartner crypto currency is active</summary>
        public bool? IsActive { get; set; }
        /// <summary>States whether the LabelPartner crypto currency is enabled</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>Name of LabelPartner crypto currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Limits for transactions - unrelated to the trustlevel of the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.TransactionLimits? TransactionLimits { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.TransactionLimits TransactionLimits { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrency"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrency CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.LabelPartnerCryptoCurrency();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockchain", n => { Blockchain = n.GetObjectValue<global::Nexus.Casp.Client.Models.Blockchain>(global::Nexus.Casp.Client.Models.Blockchain.CreateFromDiscriminatorValue); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "hotWalletReceiveFlow", n => { HotWalletReceiveFlow = n.GetEnumValue<global::Nexus.Casp.Client.Models.HotWalletReceiveFlowTypeDTO>(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "transactionLimits", n => { TransactionLimits = n.GetObjectValue<global::Nexus.Casp.Client.Models.TransactionLimits>(global::Nexus.Casp.Client.Models.TransactionLimits.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.Blockchain>("blockchain", Blockchain);
            writer.WriteStringValue("code", Code);
            writer.WriteEnumValue<global::Nexus.Casp.Client.Models.HotWalletReceiveFlowTypeDTO>("hotWalletReceiveFlow", HotWalletReceiveFlow);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.TransactionLimits>("transactionLimits", TransactionLimits);
        }
    }
}
#pragma warning restore CS0618
