// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LabelNotificationTxBuyResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cryptoCurrencyAmount property</summary>
        public decimal? CryptoCurrencyAmount { get; set; }
        /// <summary>The currencyAmount property</summary>
        public decimal? CurrencyAmount { get; set; }
        /// <summary>The sendCryptoTxId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SendCryptoTxId { get; set; }
#nullable restore
#else
        public string SendCryptoTxId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.LabelNotificationTxBuyResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cryptoCurrencyAmount", n => { CryptoCurrencyAmount = n.GetDecimalValue(); } },
                { "currencyAmount", n => { CurrencyAmount = n.GetDecimalValue(); } },
                { "sendCryptoTxId", n => { SendCryptoTxId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("cryptoCurrencyAmount", CryptoCurrencyAmount);
            writer.WriteDecimalValue("currencyAmount", CurrencyAmount);
            writer.WriteStringValue("sendCryptoTxId", SendCryptoTxId);
        }
    }
}
#pragma warning restore CS0618
