// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MailResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code of this mail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The contents of the mail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.MailContent? Content { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.MailContent Content { get; set; }
#endif
        /// <summary>The count of the mail sent</summary>
        public int? Count { get; set; }
        /// <summary>The time this mail was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The information about the recipient(s) of the mail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.MailRecipient? Recipient { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.MailRecipient Recipient { get; set; }
#endif
        /// <summary>The references to other entities (customer, account, transaction) for this mail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.MailEntityCodes? References { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.MailEntityCodes References { get; set; }
#endif
        /// <summary>The time this mail was sent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sent { get; set; }
#nullable restore
#else
        public string Sent { get; set; }
#endif
        /// <summary>The current status of the mail- `ReadyToSend`- `Sent`- `Deleted`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The type of this mail- `NewAccountRequested`- `NewAccountActivated`- `AccountDeleteRequested`- `TrustLevelUpdated`- `AccountInfoRequest`- `TransactionToBeReturned`- `TransactionReturned`- `TransactionTraded`- `TransactionSellFinish`- `TransactionBuyFinish`- `AccountDeletedByRequest`- `AccountDeletedByOperator`- `ReviewRequest`- `SendBitcoins`- `InviteFriend`- `BlockedTransaction`- `TransactionPayback`- `ComplianceInfo`- `ContactConfirm`- `PriceAlertBuyTriggered`- `PriceAlertExpired`- `PriceAlertSellTriggered`- `PromotionCodeRequested`- `PromotionCodePaid`- `TransactionBuySendDelay`- `CustNameUpdateRequest`- `WrongBankAccountWarning`- `TestPaymentSettled`- `SendGift`- `TransactionNoticed`- `NewCustomerRequested`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.MailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.MailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.MailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::Nexus.Casp.Client.Models.MailContent>(global::Nexus.Casp.Client.Models.MailContent.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "recipient", n => { Recipient = n.GetObjectValue<global::Nexus.Casp.Client.Models.MailRecipient>(global::Nexus.Casp.Client.Models.MailRecipient.CreateFromDiscriminatorValue); } },
                { "references", n => { References = n.GetObjectValue<global::Nexus.Casp.Client.Models.MailEntityCodes>(global::Nexus.Casp.Client.Models.MailEntityCodes.CreateFromDiscriminatorValue); } },
                { "sent", n => { Sent = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.MailContent>("content", Content);
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("created", Created);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.MailRecipient>("recipient", Recipient);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.MailEntityCodes>("references", References);
            writer.WriteStringValue("sent", Sent);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("type", Type);
        }
    }
}
#pragma warning restore CS0618
