// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarkAsValidatedRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The entityCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityCode { get; set; }
#nullable restore
#else
        public string EntityCode { get; set; }
#endif
        /// <summary>The environmentCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentCode { get; set; }
#nullable restore
#else
        public string EnvironmentCode { get; set; }
#endif
        /// <summary>The sanctionLists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nexus.Casp.Client.Models.MarkAsValidatedListRequest>? SanctionLists { get; set; }
#nullable restore
#else
        public List<global::Nexus.Casp.Client.Models.MarkAsValidatedListRequest> SanctionLists { get; set; }
#endif
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.MarkAsValidatedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.MarkAsValidatedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.MarkAsValidatedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entityCode", n => { EntityCode = n.GetStringValue(); } },
                { "environmentCode", n => { EnvironmentCode = n.GetStringValue(); } },
                { "sanctionLists", n => { SanctionLists = n.GetCollectionOfObjectValues<global::Nexus.Casp.Client.Models.MarkAsValidatedListRequest>(global::Nexus.Casp.Client.Models.MarkAsValidatedListRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("entityCode", EntityCode);
            writer.WriteStringValue("environmentCode", EnvironmentCode);
            writer.WriteCollectionOfObjectValues<global::Nexus.Casp.Client.Models.MarkAsValidatedListRequest>("sanctionLists", SanctionLists);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
