// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentMethodResponseModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Payment Method&apos;s code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Optional Crypto Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Optional Currency Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.PaymentMethodResponseModel_data? Data { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.PaymentMethodResponseModel_data Data { get; set; }
#endif
        /// <summary>Service and Bank fees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.PaymentMethodFees? Fees { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.PaymentMethodFees Fees { get; set; }
#endif
        /// <summary>Payment Method&apos;s name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Assigned Payment Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.PaymentType? PaymentType { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.PaymentType PaymentType { get; set; }
#endif
        /// <summary>Transaction type of the payment method.Possible values currently are:- `BUY`- `SELL`- `SENDINTERNAL`- `SENDOUT`- `SWAP`- `RECEIVEIN`- `GIFT`- `SENDTOBUCKET`- `INTEREST`- `CLAWBACK`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionType { get; set; }
#nullable restore
#else
        public string TransactionType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.PaymentMethodResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.PaymentMethodResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.PaymentMethodResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Nexus.Casp.Client.Models.PaymentMethodResponseModel_data>(global::Nexus.Casp.Client.Models.PaymentMethodResponseModel_data.CreateFromDiscriminatorValue); } },
                { "fees", n => { Fees = n.GetObjectValue<global::Nexus.Casp.Client.Models.PaymentMethodFees>(global::Nexus.Casp.Client.Models.PaymentMethodFees.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "paymentType", n => { PaymentType = n.GetObjectValue<global::Nexus.Casp.Client.Models.PaymentType>(global::Nexus.Casp.Client.Models.PaymentType.CreateFromDiscriminatorValue); } },
                { "transactionType", n => { TransactionType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.PaymentMethodResponseModel_data>("data", Data);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.PaymentMethodFees>("fees", Fees);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.PaymentType>("paymentType", PaymentType);
            writer.WriteStringValue("transactionType", TransactionType);
        }
    }
}
#pragma warning restore CS0618
