// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>&lt;ul&gt;&lt;/ul&gt;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SanctionListUploadStatus
    {
        [EnumMember(Value = "Live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "Disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
