// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SourceWithBucket : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Nexus generated unique identifier of the account or combination of crypto code and address.Example: XLM-14DuxbRVYPSmt1c3f2UnoKVUHkR5bVB9oa</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountCode { get; set; }
#nullable restore
#else
        public string AccountCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketCode { get; set; }
#nullable restore
#else
        public string BucketCode { get; set; }
#endif
        /// <summary>The amount of cryptocurrency.</summary>
        public double? CryptoAmount { get; set; }
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoCode { get; set; }
#nullable restore
#else
        public string CryptoCode { get; set; }
#endif
        /// <summary>Must be exactly 3 uppercase letters (A-Z). Example: EUR</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>Can only consist of A-Z a-z 0-9 _ -</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerCode { get; set; }
#nullable restore
#else
        public string CustomerCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.SourceWithBucket"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.SourceWithBucket CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.SourceWithBucket();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCode", n => { AccountCode = n.GetStringValue(); } },
                { "bucketCode", n => { BucketCode = n.GetStringValue(); } },
                { "cryptoAmount", n => { CryptoAmount = n.GetDoubleValue(); } },
                { "cryptoCode", n => { CryptoCode = n.GetStringValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "customerCode", n => { CustomerCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountCode", AccountCode);
            writer.WriteStringValue("bucketCode", BucketCode);
            writer.WriteDoubleValue("cryptoAmount", CryptoAmount);
            writer.WriteStringValue("cryptoCode", CryptoCode);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteStringValue("customerCode", CustomerCode);
        }
    }
}
#pragma warning restore CS0618
