// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TradePairItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>TradePair unique identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Crypto information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CryptoItem? Crypto { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CryptoItem Crypto { get; set; }
#endif
        /// <summary>Currency information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.CurrencyItem? Currency { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.CurrencyItem Currency { get; set; }
#endif
        /// <summary>Exchange information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.ExchangeItem? Exchange { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.ExchangeItem Exchange { get; set; }
#endif
        /// <summary>Price information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.PriceItem? Price { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.PriceItem Price { get; set; }
#endif
        /// <summary>Provides a comprehensive summary of all statuses of a tradepair</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nexus.Casp.Client.Models.OverallStatus? Status { get; set; }
#nullable restore
#else
        public global::Nexus.Casp.Client.Models.OverallStatus Status { get; set; }
#endif
        /// <summary>TradePair flags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Supports { get; set; }
#nullable restore
#else
        public List<string> Supports { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.TradePairItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.TradePairItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.TradePairItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "crypto", n => { Crypto = n.GetObjectValue<global::Nexus.Casp.Client.Models.CryptoItem>(global::Nexus.Casp.Client.Models.CryptoItem.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetObjectValue<global::Nexus.Casp.Client.Models.CurrencyItem>(global::Nexus.Casp.Client.Models.CurrencyItem.CreateFromDiscriminatorValue); } },
                { "exchange", n => { Exchange = n.GetObjectValue<global::Nexus.Casp.Client.Models.ExchangeItem>(global::Nexus.Casp.Client.Models.ExchangeItem.CreateFromDiscriminatorValue); } },
                { "price", n => { Price = n.GetObjectValue<global::Nexus.Casp.Client.Models.PriceItem>(global::Nexus.Casp.Client.Models.PriceItem.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Nexus.Casp.Client.Models.OverallStatus>(global::Nexus.Casp.Client.Models.OverallStatus.CreateFromDiscriminatorValue); } },
                { "supports", n => { Supports = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CryptoItem>("crypto", Crypto);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.CurrencyItem>("currency", Currency);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.ExchangeItem>("exchange", Exchange);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.PriceItem>("price", Price);
            writer.WriteObjectValue<global::Nexus.Casp.Client.Models.OverallStatus>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("supports", Supports);
        }
    }
}
#pragma warning restore CS0618
