// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nexus.Casp.Client.Models
{
    /// <summary>Transaction type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransactionTypes
    {
        [EnumMember(Value = "BUY")]
        #pragma warning disable CS1591
        BUY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELL")]
        #pragma warning disable CS1591
        SELL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENDINTERNAL")]
        #pragma warning disable CS1591
        SENDINTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENDOUT")]
        #pragma warning disable CS1591
        SENDOUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SWAP")]
        #pragma warning disable CS1591
        SWAP,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECEIVEIN")]
        #pragma warning disable CS1591
        RECEIVEIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GIFT")]
        #pragma warning disable CS1591
        GIFT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENDTOBUCKET")]
        #pragma warning disable CS1591
        SENDTOBUCKET,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTEREST")]
        #pragma warning disable CS1591
        INTEREST,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLAWBACK")]
        #pragma warning disable CS1591
        CLAWBACK,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROKERBUY")]
        #pragma warning disable CS1591
        BROKERBUY,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROKERSELL")]
        #pragma warning disable CS1591
        BROKERSELL,
        #pragma warning restore CS1591
    }
}
