// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nexus.Casp.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateCustomerPersonRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Must be a valid ISO 8601 date. Example: 2024-01-15</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateOfBirth { get; set; }
#nullable restore
#else
        public string DateOfBirth { get; set; }
#endif
        /// <summary>Array of field names to explicitly clear (set to null/empty).Supported fields: FirstName, LastName, DateOfBirth, NationalityCountryCode, ResidenceCountryCode, OwnershipPercentage,and type flags via Type.Director, Type.UltimateBeneficialOwner, Type.PseudoUltimateBeneficialOwner, Type.AuthorisedRepresentative.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FieldsToClear { get; set; }
#nullable restore
#else
        public List<string> FieldsToClear { get; set; }
#endif
        /// <summary>Update the first name of the person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Update the last name of the person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Update the country code of this person&apos;s nationality (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NationalityCountryCode { get; set; }
#nullable restore
#else
        public string NationalityCountryCode { get; set; }
#endif
        /// <summary>Update the person&apos;s ownership percentage of the business - only applicable for ultimate beneficial owner type of persons. Ownership percentage should be expressed as a decimal fraction.</summary>
        public decimal? OwnershipPercentage { get; set; }
        /// <summary>Update the country code of this person&apos;s residence country (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResidenceCountryCode { get; set; }
#nullable restore
#else
        public string ResidenceCountryCode { get; set; }
#endif
        /// <summary>Update the ways a person is linked to a customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nexus.Casp.Client.Models.CustomerPersonTypeDTO?>? Types { get; set; }
#nullable restore
#else
        public List<global::Nexus.Casp.Client.Models.CustomerPersonTypeDTO?> Types { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.UpdateCustomerPersonRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nexus.Casp.Client.Models.UpdateCustomerPersonRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nexus.Casp.Client.Models.UpdateCustomerPersonRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dateOfBirth", n => { DateOfBirth = n.GetStringValue(); } },
                { "fieldsToClear", n => { FieldsToClear = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "nationalityCountryCode", n => { NationalityCountryCode = n.GetStringValue(); } },
                { "ownershipPercentage", n => { OwnershipPercentage = n.GetDecimalValue(); } },
                { "residenceCountryCode", n => { ResidenceCountryCode = n.GetStringValue(); } },
                { "types", n => { Types = n.GetCollectionOfEnumValues<global::Nexus.Casp.Client.Models.CustomerPersonTypeDTO>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dateOfBirth", DateOfBirth);
            writer.WriteCollectionOfPrimitiveValues<string>("fieldsToClear", FieldsToClear);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteStringValue("nationalityCountryCode", NationalityCountryCode);
            writer.WriteDecimalValue("ownershipPercentage", OwnershipPercentage);
            writer.WriteStringValue("residenceCountryCode", ResidenceCountryCode);
            writer.WriteCollectionOfEnumValues<global::Nexus.Casp.Client.Models.CustomerPersonTypeDTO>("types", Types);
        }
    }
}
#pragma warning restore CS0618
