// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals
{
    /// <summary>
    /// Builds and executes requests for operations under \interest\custodian\schedules\{scheduleId}\subintervals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubintervalsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nexus.Casp.Client.interest.custodian.schedules.item.subintervals.item collection</summary>
        /// <param name="position">Type of Interval</param>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.Item.WithTypeItemRequestBuilder"/></returns>
        public global::Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.SubintervalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubintervalsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interest/custodian/schedules/{scheduleId}/subintervals", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Interest.Custodian.Schedules.Item.Subintervals.SubintervalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubintervalsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interest/custodian/schedules/{scheduleId}/subintervals", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
