// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag
{
    /// <summary>
    /// Builds and executes requests for operations under \paymentmethod\{paymentMethodCode}\fees\tag
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nexus.Casp.Client.paymentmethod.item.fees.tag.item collection</summary>
        /// <param name="position">Customer tag for the fee.</param>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.Item.WithCustomerTagItemRequestBuilder"/></returns>
        public global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.Item.WithCustomerTagItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("customerTag", position);
                return new global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.Item.WithCustomerTagItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/paymentmethod/{paymentMethodCode}/fees/tag{?CustomerTag*,Limit*,Page*,SortDirection*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/paymentmethod/{paymentMethodCode}/fees/tag{?CustomerTag*,Limit*,Page*,SortDirection*}", rawUrl)
        {
        }
        /// <summary>
        /// List payment method tag fees
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponsePagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponsePagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder.TagRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponsePagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder.TagRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponsePagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponsePagedResultCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert a payment method tag fee
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponseCustomResultHolder"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponseCustomResultHolder?> PutAsync(global::Nexus.Casp.Client.Models.UpsertPaymentMethodTagFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponseCustomResultHolder> PutAsync(global::Nexus.Casp.Client.Models.UpsertPaymentMethodTagFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponseCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.PaymentMethodTagFeeResponseCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List payment method tag fees
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder.TagRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder.TagRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Upsert a payment method tag fee
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Nexus.Casp.Client.Models.UpsertPaymentMethodTagFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Nexus.Casp.Client.Models.UpsertPaymentMethodTagFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Tag.TagRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List payment method tag fees
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by a specific Customer tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? CustomerTag { get; set; }
#nullable restore
#else
            public string CustomerTag { get; set; }
#endif
            /// <summary>The page limit</summary>
            public int? Limit { get; set; }
            /// <summary>Get specific page of payment method tag fees</summary>
            public int? Page { get; set; }
            /// <summary>Sort payment method tag fees result direction. Defaults to `Asc`Possible values:- `Asc` (Ascending)- `Desc` (Descending)</summary>
            public global::Nexus.Casp.Client.Models.SortDirection? SortDirection { get; set; }
        }
    }
}
#pragma warning restore CS0618
