// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using Nexus.Casp.Client.Orders.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Orders
{
    /// <summary>
    /// Builds and executes requests for operations under \Orders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nexus.Casp.Client.Orders.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Orders.Item.WithOrderCodeItemRequestBuilder"/></returns>
        public global::Nexus.Casp.Client.Orders.Item.WithOrderCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orderCode", position);
                return new global::Nexus.Casp.Client.Orders.Item.WithOrderCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Orders{?actionType*,amountFrom*,amountTo*,createdFrom*,createdTill*,cryptoCode*,currencyCode*,exchangeCode*,finishedFrom*,finishedTill*,isPartial*,limit*,orderCode*,orderType*,page*,sortBy*,sortDirection*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Orders{?actionType*,amountFrom*,amountTo*,createdFrom*,createdTill*,cryptoCode*,currencyCode*,exchangeCode*,finishedFrom*,finishedTill*,isPartial*,limit*,orderCode*,orderType*,page*,sortBy*,sortDirection*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// List orders
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetOrderPagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.GetOrderPagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.GetOrderPagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.GetOrderPagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.GetOrderPagedResultCustomResultHolder.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiate order
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder?> PostAsync(global::Nexus.Casp.Client.Models.CreateOrder body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder> PostAsync(global::Nexus.Casp.Client.Models.CreateOrder body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.GetOrderCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List orders
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Initiate order
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Nexus.Casp.Client.Models.CreateOrder body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Nexus.Casp.Client.Models.CreateOrder body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Orders.OrdersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Orders.OrdersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Orders.OrdersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List orders
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter on action.Possible order action types:- `Buy`- `Sell`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("actionType")]
            public string? ActionType { get; set; }
#nullable restore
#else
            [QueryParameter("actionType")]
            public string ActionType { get; set; }
#endif
            /// <summary>Filter on equal or more than minimun amount.</summary>
            [QueryParameter("amountFrom")]
            public decimal? AmountFrom { get; set; }
            /// <summary>Filter on less than maximum amount.</summary>
            [QueryParameter("amountTo")]
            public decimal? AmountTo { get; set; }
            /// <summary>Filter on Created on or after the createdFrom (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdFrom")]
            public string? CreatedFrom { get; set; }
#nullable restore
#else
            [QueryParameter("createdFrom")]
            public string CreatedFrom { get; set; }
#endif
            /// <summary>Filter on Created upto the createdTill (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdTill")]
            public string? CreatedTill { get; set; }
#nullable restore
#else
            [QueryParameter("createdTill")]
            public string CreatedTill { get; set; }
#endif
            /// <summary>Filter on crypto.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cryptoCode")]
            public string? CryptoCode { get; set; }
#nullable restore
#else
            [QueryParameter("cryptoCode")]
            public string CryptoCode { get; set; }
#endif
            /// <summary>Filter on currency (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("currencyCode")]
            public string? CurrencyCode { get; set; }
#nullable restore
#else
            [QueryParameter("currencyCode")]
            public string CurrencyCode { get; set; }
#endif
            /// <summary>Filter on trade exchange.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("exchangeCode")]
            public string? ExchangeCode { get; set; }
#nullable restore
#else
            [QueryParameter("exchangeCode")]
            public string ExchangeCode { get; set; }
#endif
            /// <summary>Filter on Finished on or after the finishedFrom (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("finishedFrom")]
            public string? FinishedFrom { get; set; }
#nullable restore
#else
            [QueryParameter("finishedFrom")]
            public string FinishedFrom { get; set; }
#endif
            /// <summary>Filter on Created upto the finishedTill (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("finishedTill")]
            public string? FinishedTill { get; set; }
#nullable restore
#else
            [QueryParameter("finishedTill")]
            public string FinishedTill { get; set; }
#endif
            /// <summary>Filter on if the order was partially executed.</summary>
            [QueryParameter("isPartial")]
            public bool? IsPartial { get; set; }
            /// <summary>The number of orders returned per page.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter on order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderCode")]
            public string? OrderCode { get; set; }
#nullable restore
#else
            [QueryParameter("orderCode")]
            public string OrderCode { get; set; }
#endif
            /// <summary>Filter on type.Possible order types:- `Market`- `Limit`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderType")]
            public string? OrderType { get; set; }
#nullable restore
#else
            [QueryParameter("orderType")]
            public string OrderType { get; set; }
#endif
            /// <summary>Get specific page of orders.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Property upon which the orders will be sorted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortBy")]
            public string? SortBy { get; set; }
#nullable restore
#else
            [QueryParameter("sortBy")]
            public string SortBy { get; set; }
#endif
            /// <summary>Direction of sort.Possible values:- `Asc`- `Desc`</summary>
            [QueryParameter("sortDirection")]
            public global::Nexus.Casp.Client.Models.SortDirection? SortDirection { get; set; }
            /// <summary>Filter on status.Possible order statuses:- `Initiated`- `Queued`- `Open`- `ToCancel`- `Filled`- `Rejected`- `Expired`- `Cancelled`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
