// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Sendout.Custodian;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Sendout
{
    /// <summary>
    /// Builds and executes requests for operations under \sendout
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendoutRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custodian property</summary>
        public global::Nexus.Casp.Client.Sendout.Custodian.CustodianRequestBuilder Custodian
        {
            get => new global::Nexus.Casp.Client.Sendout.Custodian.CustodianRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sendout.SendoutRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendoutRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sendout", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sendout.SendoutRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendoutRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sendout", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
