// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Customer.Item.Limits.Broker.Buy;
using Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Customer.Item.Limits.Broker
{
    /// <summary>
    /// Builds and executes requests for operations under \Customer\{customerCode}\limits\broker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BrokerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The buy property</summary>
        public global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Buy.BuyRequestBuilder Buy
        {
            get => new global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Buy.BuyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sell property</summary>
        public global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder Sell
        {
            get => new global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Limits.Broker.BrokerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BrokerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Customer/{customerCode}/limits/broker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Limits.Broker.BrokerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BrokerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Customer/{customerCode}/limits/broker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
