// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Sanction.Validatedentry.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sanction\validatedentry\{list}\{entityCode}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityCodeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityCodeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sanction/validatedentry/{list}/{entityCode}{?EnvironmentCode*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityCodeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sanction/validatedentry/{list}/{entityCode}{?EnvironmentCode*}", rawUrl)
        {
        }
        /// <summary>
        /// Soft-delete validated entries for an entity in the specified sanction list.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get active validated entries for an entity in the specified sanction list.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetValidatedEntryResponseIEnumerableCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.GetValidatedEntryResponseIEnumerableCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.GetValidatedEntryResponseIEnumerableCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.GetValidatedEntryResponseIEnumerableCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.GetValidatedEntryResponseIEnumerableCustomResultHolder.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Soft-delete validated entries for an entity in the specified sanction list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Get active validated entries for an entity in the specified sanction list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder.WithEntityCodeItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Sanction.Validatedentry.Item.Item.WithEntityCodeItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Soft-delete validated entries for an entity in the specified sanction list.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEntityCodeItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Optional environment qualifier (e.g. TEST, PROD).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? EnvironmentCode { get; set; }
#nullable restore
#else
            public string EnvironmentCode { get; set; }
#endif
        }
        /// <summary>
        /// Get active validated entries for an entity in the specified sanction list.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEntityCodeItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Optional environment qualifier (e.g. TEST, PROD).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? EnvironmentCode { get; set; }
#nullable restore
#else
            public string EnvironmentCode { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
