// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Customer.Item.Comments.Item.History;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Customer.Item.Comments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \customer\{customerCode-id}\comments\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommentsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The history property</summary>
        public global::Nexus.Casp.Client.Customer.Item.Comments.Item.History.HistoryRequestBuilder History
        {
            get => new global::Nexus.Casp.Client.Customer.Item.Comments.Item.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.Item.CommentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode%2Did}/comments/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Comments.Item.CommentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode%2Did}/comments/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
