// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell
{
    /// <summary>
    /// Builds and executes requests for operations under \Customer\{customerCode}\limits\broker\sell
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SellRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SellRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Customer/{customerCode}/limits/broker/sell{?cryptoCode*,currencyCode*,paymentMethodCode*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SellRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Customer/{customerCode}/limits/broker/sell{?cryptoCode*,currencyCode*,paymentMethodCode*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the current spending limit expressed in fiat.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.GetBrokerLimitResponseCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.GetBrokerLimitResponseCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder.SellRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.GetBrokerLimitResponseCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder.SellRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.GetBrokerLimitResponseCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.GetBrokerLimitResponseCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the current spending limit expressed in fiat.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder.SellRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder.SellRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Customer.Item.Limits.Broker.Sell.SellRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the current spending limit expressed in fiat.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SellRequestBuilderGetQueryParameters 
        {
            /// <summary>The crypto currency code the customer limit is calculated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cryptoCode")]
            public string? CryptoCode { get; set; }
#nullable restore
#else
            [QueryParameter("cryptoCode")]
            public string CryptoCode { get; set; }
#endif
            /// <summary>The currency code the limits are shown in (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("currencyCode")]
            public string? CurrencyCode { get; set; }
#nullable restore
#else
            [QueryParameter("currencyCode")]
            public string CurrencyCode { get; set; }
#endif
            /// <summary>The payment method code the customer limit is calculated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("paymentMethodCode")]
            public string? PaymentMethodCode { get; set; }
#nullable restore
#else
            [QueryParameter("paymentMethodCode")]
            public string PaymentMethodCode { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
