// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Customer.Item.Nonnativeaccount
{
    /// <summary>
    /// Builds and executes requests for operations under \customer\{customerCode}\nonnativeaccount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NonnativeaccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Nonnativeaccount.NonnativeaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NonnativeaccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode}/nonnativeaccount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Customer.Item.Nonnativeaccount.NonnativeaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NonnativeaccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/{customerCode}/nonnativeaccount", rawUrl)
        {
        }
        /// <summary>
        /// Create non-native account
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.CreateAccountResponseCustomResultHolder"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.StringArrayCustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.CreateAccountResponseCustomResultHolder?> PostAsync(global::Nexus.Casp.Client.Models.CreateNonNativeAccountModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.CreateAccountResponseCustomResultHolder> PostAsync(global::Nexus.Casp.Client.Models.CreateNonNativeAccountModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.StringArrayCustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.CreateAccountResponseCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.CreateAccountResponseCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create non-native account
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Nexus.Casp.Client.Models.CreateNonNativeAccountModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Nexus.Casp.Client.Models.CreateNonNativeAccountModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Customer.Item.Nonnativeaccount.NonnativeaccountRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Customer.Item.Nonnativeaccount.NonnativeaccountRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Customer.Item.Nonnativeaccount.NonnativeaccountRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
