// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Transaction.Item.Callbacks
{
    /// <summary>
    /// Builds and executes requests for operations under \Transaction\{txCode}\callbacks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CallbacksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallbacksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Transaction/{txCode}/callbacks{?limit*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallbacksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Transaction/{txCode}/callbacks{?limit*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// Get callback notifications for the transaction
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.TransactionNotificationCallbackResponsePagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.TransactionNotificationCallbackResponsePagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder.CallbacksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.TransactionNotificationCallbackResponsePagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder.CallbacksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.TransactionNotificationCallbackResponsePagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.TransactionNotificationCallbackResponsePagedResultCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get callback notifications for the transaction
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder.CallbacksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder.CallbacksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Transaction.Item.Callbacks.CallbacksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get callback notifications for the transaction
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CallbacksRequestBuilderGetQueryParameters 
        {
            /// <summary>Enter page limit.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Get specific page of callback notifications.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
    }
}
#pragma warning restore CS0618
