// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Models;
using Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer
{
    /// <summary>
    /// Builds and executes requests for operations under \paymentmethod\{paymentMethodCode}\fees\customer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nexus.Casp.Client.paymentmethod.item.fees.customer.item collection</summary>
        /// <param name="position">Customer code for the fee.</param>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.Item.WithCustomerCodeItemRequestBuilder"/></returns>
        public global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.Item.WithCustomerCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("customerCode", position);
                return new global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.Item.WithCustomerCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/paymentmethod/{paymentMethodCode}/fees/customer{?CustomerCode*,Limit*,Page*,SortDirection*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/paymentmethod/{paymentMethodCode}/fees/customer{?CustomerCode*,Limit*,Page*,SortDirection*}", rawUrl)
        {
        }
        /// <summary>
        /// List payment method customer fees
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponsePagedResultCustomResultHolder"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponsePagedResultCustomResultHolder?> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder.CustomerRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponsePagedResultCustomResultHolder> GetAsync(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder.CustomerRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponsePagedResultCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponsePagedResultCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert a payment method customer fee
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponseCustomResultHolder"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 400 status code</exception>
        /// <exception cref="global::Nexus.Casp.Client.Models.CustomResultHolder">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponseCustomResultHolder?> PutAsync(global::Nexus.Casp.Client.Models.UpsertPaymentMethodCustomerFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponseCustomResultHolder> PutAsync(global::Nexus.Casp.Client.Models.UpsertPaymentMethodCustomerFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
                { "404", global::Nexus.Casp.Client.Models.CustomResultHolder.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponseCustomResultHolder>(requestInfo, global::Nexus.Casp.Client.Models.PaymentMethodCustomerFeeResponseCustomResultHolder.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List payment method customer fees
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder.CustomerRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder.CustomerRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Upsert a payment method customer fee
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Nexus.Casp.Client.Models.UpsertPaymentMethodCustomerFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Nexus.Casp.Client.Models.UpsertPaymentMethodCustomerFeeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nexus.Casp.Client.Paymentmethod.Item.Fees.Customer.CustomerRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List payment method customer fees
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomerRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by a specific Customer code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? CustomerCode { get; set; }
#nullable restore
#else
            public string CustomerCode { get; set; }
#endif
            /// <summary>The page limit</summary>
            public int? Limit { get; set; }
            /// <summary>Get specific page of payment method customer fees</summary>
            public int? Page { get; set; }
            /// <summary>Sort payment method customer fees result direction. Defaults to `Asc`Possible values:- `Asc` (Ascending)- `Desc` (Descending)</summary>
            public global::Nexus.Casp.Client.Models.SortDirection? SortDirection { get; set; }
        }
    }
}
#pragma warning restore CS0618
