// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nexus.Casp.Client.Swap.Custodian;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nexus.Casp.Client.Swap
{
    /// <summary>
    /// Builds and executes requests for operations under \swap
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SwapRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custodian property</summary>
        public global::Nexus.Casp.Client.Swap.Custodian.CustodianRequestBuilder Custodian
        {
            get => new global::Nexus.Casp.Client.Swap.Custodian.CustodianRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Swap.SwapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SwapRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/swap", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nexus.Casp.Client.Swap.SwapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SwapRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/swap", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
