# This workflow will build a .NET project and publish a NuGet package to GitHub Packages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack NuGet package
      run: dotnet pack --no-build --output ./nupkg
    - name: Determine Version
      id: version
      run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}""
    - name: Package and Deploy
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      env:
        NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        VERSION=${VERSION#"v"}
        dotnet pack -p:PackageVersion=$VERSION -c Release
        dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://nuget.pkg.github.com/QuantozTechnology/index.json
